config/routes.rb
BoleteriApp::Application.routes.draw do

  devise_for :users, :path_names => { :sign_up => "registro", :sign_in => "entrar",
                                      :sign_out => "salir"}

  resources :hotels

  resources :travels do
    resources :hotels
  end
  
  match "/travels/compra/:id" => "travels#compra"

  root :to => 'home#index' do
    resources :travels
  end

end

app/models/travel.rb
class Travel < ActiveRecord::Base
  attr_accessible :destination_city, :destination_country, :detail, :extract, :n_days, :n_nights, :number_of_seats_aviables, :price, :quota_attributes
  
  attr_accessor :hotels

	validates :destination_city, :destination_country, :detail, :extract, :n_days, :n_nights, :number_of_seats_aviables,	:presence => true
	validates :destination_country,	:length	=> {:minimum => 4, :maximum => 59} #de acuerdo a los paises con los combres mas cortos y nombres mas largos
	validates	:destination_city,		:length => {:minimum => 1, :maximum => 85}
  validates :number_of_seats_aviables, :numericality => { :only_integer => true , :greater_than_or_equal_to => 5}
  validates :price, :numericality => :true
	
	has_one :quota
	has_many :tickets
	has_one :hotel, :through => :quota
  
  accepts_nested_attributes_for :quota, :allow_destroy => :true
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  # GET /travels
  # GET /travels.json
  def index
    @travels = Travel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @travels }
    end
  end

  # GET /travels/1
  # GET /travels/1.json
  def show
    @travel = Travel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @travel }
    end
  end

  # GET /travels/new
  # GET /travels/new.json
  def new
    @travel = Travel.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @travel }
    end
  end

  # GET /travels/1/edit
  def edit
    @travel = Travel.find(params[:id])
  end

  # POST /travels
  # POST /travels.json
  def create
    @travel = Travel.new(params[:travel])
    respond_to do |format|
      if @travel.save
        format.html { redirect_to @travel, notice: 'Travel was successfully created.' }
        format.json { render json: @travel, status: :created, location: @travel }
      else
        format.html { render action: "new" }
        format.json { render json: @travel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /travels/1
  # PUT /travels/1.json
  def update
    @travel = Travel.find(params[:id])

    respond_to do |format|
      if @travel.update_attributes(params[:travel])
        format.html { redirect_to @travel, notice: 'Travel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @travel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /travels/1
  # DELETE /travels/1.json
  def destroy
    @travel = Travel.find(params[:id])
    @travel.destroy

    respond_to do |format|
      format.html { redirect_to travels_url }
      format.json { head :no_content }
    end
  end
  
  #DELETE /travels/compra/1
  #DELETE /travels/compra/1.json
  def compra
    @travel = Travel.find(params[:id])

    respond_to do |format|
      format.html # compra.html.erb
      format.json { render json: @travel }
    end
  end
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/views/travels/_form.html.erb
<%= form_for(@travel) do |f| %>
  <% if @travel.errors.any? %>
    <div class="alert alert-block alert-error fade in">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h2><%= pluralize(@travel.errors.count, "error") %> No se puede guardar este <b>viaje</b> porque:</h2>

      <ul>
      <% @travel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :destination_city %>
    <%= f.text_field :destination_city %>
  </div>
  <div class="field">
    <%= f.label :destination_country %>
    <%= f.text_field :destination_country %>
  </div>
  <div class="field">
    <%= f.label :n_days %>
    <%= f.number_field :n_days %>
  </div>
  <div class="field">
    <%= f.label :n_nights %>
    <%= f.number_field :n_nights %>
  </div>
  <div class="field">
    <%= f.label :extract %>
    <%= f.text_area :extract %>
  </div>
  <div class="field">
    <%= f.label :detail %>
    <%= f.text_area :detail %>
  </div>
  <div class="field">
    <%= f.label :number_of_seats_aviables %>
    <%= f.number_field :number_of_seats_aviables %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/travels/compra.html.erb
<h2>¿Interesado en comprar un pasaje a <%= @travel.destination_city %>, <%= @travel.destination_country %>?</h2>
<h4>Precio: <%= number_to_currency(@travel.price) %> por persona</h4>

app/views/travels/edit.html.erb
<h1>Edita los datos del viaje</h1>

<%= render 'form' %>

<%= link_to 'Show', @travel %> |
<%= link_to 'Back', travels_path %>

app/views/travels/index.html.erb
<h1>Nuestro catalogo de viajes</h1>
<div class="row-fluid">
<ul class="thumbnails">
<% @travels.each do |travel| %>
  <li class="span4">
    <div class="thumbnail">
      <img data-src="holder.js/300x200" alt="300x200" style="width: 300px; height: 200px;" src="images/300x200.png">
      <div class="caption">
        <h3><%= travel.destination_city %></h3>
        <h5><%= travel.destination_country%></h5>
          <p><%= travel.extract %></p>
          <p><%= link_to "ver mas..", travel, html_options = {:class => "btn"} %></p>
      </div>
    </div>
  </li>
<% end %>
</ul>
</div>

<br />

<%= link_to 'New Travel', new_travel_path %>

app/views/travels/new.html.erb
<h1>Nuevo Viaje</h1>

<%= render 'form' %>

<%= link_to 'Atrás', travels_path %>

app/views/travels/show.html.erb
<p>
  <b><%= t 'activerecord.attributes.travel.destination_city' %>:</b>
  <%= @travel.destination_city %>
</p>

<p>
  <b><%= t 'activerecord.attributes.travel.destination_country' %>:</b>
  <%= @travel.destination_country %>
</p>
<p>
  <b><%= t 'activerecord.attributes.travel.price' %>:</b>
  <%= number_to_currency(@travel.price) %>
</p>
<p>
  <b><%= t 'activerecord.attributes.travel.n_days' %>:</b>
  <%= @travel.n_days %>
</p>

<p>
  <b><%= t 'activerecord.attributes.travel.n_nights' %>:</b>
  <%= @travel.n_nights %>
</p>

<p>
  <b><%= t 'activerecord.attributes.travel.extract' %>:</b>
  <%= @travel.extract %>
</p>

<p>
  <b><%= t 'activerecord.attributes.travel.detail' %>:</b>
  <%= @travel.detail %>
</p>

<%= link_to 'Comprar', { :controller => 'travels', :action => 'compra', :id => @travel.id }, html_options = {:class => "btn btn-success"} %> 
<%= link_to 'Editar', edit_travel_path(@travel), html_options = { :class => "btn" } %> 
<%= link_to 'Atrás', travels_path, html_options = { :class => "btn" } %>