config/routes.rb
BoleteriApp::Application.routes.draw do

  devise_for :users, :path_names => { :sign_up => "registro", :sign_in => "entrar",
                                      :sign_out => "salir"}

  resources :hotels

  resources :travels do
    resources :hotels
  end
  
  match "/travels/compra/:id" => "travels#compra"

  root :to => 'home#index' do
    resources :travels
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
		if !User.where(:user_type => "admin").exists? #En caso de que no haya usuarios se envía a crear un administrador
			redirect_to '/users/registro'
		end
     @travels = Travel.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_travel_panel.html.erb
<ul class="thumbnails">
<% @travels.each do |travel| %>
  <li class="span4">
    <div class="thumbnail">
      <img data-src="holder.js/300x200" alt="300x200" style="width: 300px; height: 200px;" src="images/300x200.png">
      <div class="caption">
        <h3><%= travel.destination_city %></h3>
        <h5><%= travel.destination_country%></h5>
        <h6>por tan solo <%= number_to_currency(travel.price , :locale => :es) %></h6>
          <p><%= travel.extract %></p>
          <p><%= link_to "ver mas..", travel, html_options = {:class => "btn"} %> 
          <% if user_signed_in? %>
            <% if current_user.admin? %>
           <%= link_to "editar", edit_travel_path(travel), html_options = { :class => "btn btn-warning"} %>
            <% end %>
           <%= link_to "comprar", { :controller => 'travels', :action => 'compra', :id => travel.id }, html_options = {:class => "btn btn-success"}%>
          <% end %>
          </p>
      </div>
    </div>
  </li>
<% end %>
</ul>

app/views/home/index.html.erb
<h1>Bienvenido</h1>
<p>Disfruta de nuestros paquetes y ofertas...</p>
<div class="row-fluid">
<% if user_signed_in? and current_user.admin? and @travels.nil?%>
  <div class="alert alert-block">
  <h4>No existe ningún viaje...</h4>
    <p>
      Por favor, crea un hotel y luego un viaje.
    </p>
    <p>
      <%= link_to "Crear hotel", new_hotel_path, html_options = {:class => "btn btn-primary"} %> <%= link_to "Crear viaje", new_travel_path, html_options = {:class => "btn btn-primary"} %>
    </p>
  </div>
<% end %>
<% if !@travels.nil?%>  
<%= render 'travel_panel'%>
<% end %>
</div>