config/routes.rb
BoleteriApp::Application.routes.draw do

  devise_for :users, :path_names => { :sign_up => "registro", :sign_in => "entrar",
                                      :sign_out => "salir"}

  resources :hotels

  resources :travels do
    resources :hotels
  end
  
  match "/travels/compra/:id" => "travels#compra"

  root :to => 'home#index' do
    resources :travels
  end

end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hotels }
    end
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
    @hotel = Hotel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hotel }
    end
  end

  # GET /hotels/new
  # GET /hotels/new.json
  def new
    @hotel = Hotel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hotel }
    end
  end

  # GET /hotels/1/edit
  def edit
    @hotel = Hotel.find(params[:id])
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(params[:hotel])

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render json: @hotel, status: :created, location: @hotel }
      else
        format.html { render action: "new" }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hotels/1
  # PUT /hotels/1.json
  def update
    @hotel = Hotel.find(params[:id])

    respond_to do |format|
      if @hotel.update_attributes(params[:hotel])
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy

    respond_to do |format|
      format.html { redirect_to hotels_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/hotels_helper.rb
module HotelsHelper
  def join_assets(hotel)
    hotel.assets.map { |t| t.name }.join(", ")
  end
end

app/views/hotels/_form.html.erb
<% @hotel.assets.build %>
<%= form_for(@hotel) do |f| %>
  <% if @hotel.errors.any? %>
    <div class="alert alert-block alert-error fade in">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h2><%= pluralize(@hotel.errors.count, "error") %> evitaron salvareste hotel:</h2>

      <ul>
      <% @hotel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :number_of_rooms_single %><br />
    <%= f.number_field :number_of_rooms_single %>
  </div>
  <div class="field">
    <%= f.label :number_of_rooms_doubles %><br />
    <%= f.number_field :number_of_rooms_doubles %>
  </div>
  <div class="field">
    <%= f.label :number_of_rooms_married %><br />
    <%= f.number_field :number_of_rooms_married %>
  </div>
  <%= render :partial => 'assets/form', :locals => { :form => f }%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>

<%= render 'form' %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<h1>Listing hotels</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Country</th>
    <th>City</th>
    <th>Number of rooms single</th>
    <th>Number of rooms doubles</th>
    <th>Number of rooms married</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hotels.each do |hotel| %>
  <tr>
    <td><%= hotel.name %></td>
    <td><%= hotel.country %></td>
    <td><%= hotel.city %></td>
    <td><%= hotel.number_of_rooms_single %></td>
    <td><%= hotel.number_of_rooms_doubles %></td>
    <td><%= hotel.number_of_rooms_married %></td>
    <td><%= link_to 'Show', hotel %></td>
    <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
    <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hotel', new_hotel_path %>

app/views/hotels/new.html.erb
<h1>Nuevo Hotel</h1>

<%= render 'form' %>

<%= link_to 'Atrás', hotels_path %>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= t 'activerecord.attributes.hotel.name'%>:</b>
  <%= @hotel.name %>
</p>

<p>
  <b><%= t 'activerecord.attributes.hotel.country'%>:</b>
  <%= @hotel.country %>
</p>

<p>
  <b><%= t 'activerecord.attributes.hotel.city'%>:</b>
  <%= @hotel.city %>
</p>

<p>
  <b><%= t 'activerecord.attributes.hotel.number_of_rooms_single'%>:</b>
  <%= @hotel.number_of_rooms_single %>
</p>

<p>
  <b><%= t 'activerecord.attributes.hotel.number_of_rooms_doubles' %>:</b>
  <%= @hotel.number_of_rooms_doubles %>
</p>

<p>
  <b><%= t 'activerecord.attributes.hotel.number_of_rooms_married'%>:</b>
  <%= @hotel.number_of_rooms_married %>
</p>
<p>
	<b><%= t 'activerecord.attributes.hotel.assets'%>:</b>
	<%= join_assets(@hotel)%>
</p>


<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %>